[project]
name = "eisyfit-wepy"
version = "0.1.1"
description = "EIS-specific electrochemical data-processing utilities"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Jaroslav Herman" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Chemistry",
]
requires-python = ">=3.14"
dependencies = [
    "eisyfit-bayes-drt2",
    "eisyfit-galvani",
    "eisyfit-hybrid-drt",
    "impedance>=1.7.1",
    "matplotlib>=3.11.1",
    "natsort>=8.4.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
]

[project.urls]
Homepage = "https://github.com/jaroslav-herman/wepy"
Repository = "https://github.com/jaroslav-herman/wepy"
Issues = "https://github.com/jaroslav-herman/wepy/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
wepy = ["py.typed"]
