[project]
name = "wepy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bayes-drt2",
    "galvani",
    "hybrid-drt",
    "impedance>=1.7.1",
    "matplotlib>=3.11.1",
    "mittag-leffler",
    "natsort>=8.4.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
]

[tool.uv.sources]
mittag-leffler = { git = "https://github.com/jdhuang-csm/mittag-leffler" }
hybrid-drt = { git = "https://github.com/jdhuang-csm/hybrid-drt" }
bayes-drt2 = { git = "https://github.com/jaroslav-herman/bayes-drt2" }
galvani = { path = "../galvani", editable = true }
